export const cartActionTypes = {
    ADD_ITEM_TO_CART: 'ADD_ITEM_TO_CART',
    REMOVE_ITEM_FROM_CART: 'REMOVE_ITEM_FROM_CART',
    DELETE_ITEM_FROM_CART: 'DELETE_ITEM_FROM_CART',
    GET_ACCUMULATED_QUANTITY: 'GET_ACCUMULATED_QUANTITY'
}